# Site Settings
title: Ben got MoviePass!!
email: itsame@benhu.me
description: Basically coming of age movies are instant 4 stars
baseurl: "/movies" # the subpath of your site, e.g. /blog
url: "http://benhu.me" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: ben hu
user_description: unqualified opinions
# disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
#github_username: github_username
facebook_username: huisben
twitter_username: imbenhu
instagram_username: huisben
linkedin_username: huben
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
